version: '3'
services:
  app:
    container_name: docker-test
    restart: always
    build: .
    ports:
      - '8000:3000'
    links:
      - mongo
    environment:
      - MONGO_HOST: mongodb
      - PORT: '3000'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
