version: '3'
services:
  app:
    container_name: docker-test
    restart: always
    build: .
    ports:
      - '8000:3000'
    links:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      PORT: 3000

  mongodb:
    container_name: mongo-test
    image: mongo
    ports:
      - '27017:27017'
